package com.find.the.diffrence;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and
then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e

Explanation:
'e' is the letter that was added.
*/

import java.util.Set;
import java.util.stream.Collectors;

public class Main {
    public static void main(String[] args) {
        System.out.println(Solution.difference("abcd", "abcde"));
    }
}

class Solution {
    public static char difference(String s, String t) {
        Set<Character> set = s.chars().mapToObj(i -> (char) i).collect(Collectors.toSet());
        for (char c : t.toCharArray()) if(!set.contains(c)) return c;
        return '!';
    }
}